#!/usr/bin/bash

# Define the clock
Clock() {
        DATETIME=$(date "+%a %b %d, %T")

        echo -n "$DATETIME"
}

# Print the clock

while true; do
        echo "%{r}%{F#606261}%{B#d3d7d5} $(Clock) %{F-}%{B-}"
        sleep 1
done
