#!/usr/bin/bash

#Define the battery
Battery() {
	BATPERC=$(acpi --battery | cut -d, -f2)
        echo "$BATPERC"
}


# Define the clock
Clock() {
        DATETIME=$(date "+%a %b, %T")

        echo -n "$DATETIME"
}

# Print the clock and date at the same time

while true; do
	echo "%{F#606261}%{B#d3d7d5}%{l}$(Battery)%{F-}%{B-}%{r}%{F#606261}%{B#d3d7d5} $(Clock) %{F-}%{B-}"
        sleep 1
done
