#! /bin/sh

bspc config border_width        5
bspc config window_gap          10

bspc config normal_border_color "#D68189"
bspc config active_border_color "#b9b9b9"
bspc config focused_border_color "#E94E77"
bspc config presel_feedback_color "#888888"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          12
bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc rule -a mpv desktop=focused follow=on state=floating
bspc rule -a gpicview desktop=focused follow=on state=floating
bspc rule -a Gpicview desktop=focused follow=on state=floating
bspc rule -a tk follow=off state=floating
bspc rule -a Tk follow=off state=floating
bspc rule -a anki follow=on state=floating
bspc rule -a Anki follow=on state=floating
bspc rule -a Steam desktop=^4 follow=on state=floating
bspc rule -a gimp follow=on state=floating
bspc rule -a Gimp follow=on state=floating

bspc monitor eDP1 -d 1 2 3 4 5

sh ~/.config/lemonbar/bar.sh &

