#! /bin/sh

bspc config border_width        4
bspc config window_gap          10

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

#bspc config normal_border_color "#D68189"
#bspc config active_border_color "#b9b9b9"
#bspc config focused_border_color "#E94E77"
#bspc config presel_feedback_color "#888888"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          11
bspc config focus_follows_pointer false
bspc config click_to_focus true

bspc rule -a mpv desktop=focused follow=on state=floating
bspc rule -a gpicview desktop=focused follow=on state=floating
bspc rule -a Gpicview desktop=focused follow=on state=floating
bspc rule -a tk follow=off state=floating
bspc rule -a Tk follow=off state=floating
bspc rule -a anki follow=on state=floating
bspc rule -a Anki follow=on state=floating
bspc rule -a Steam follow=on state=floating
bspc rule -a gimp follow=on state=floating
bspc rule -a Gimp follow=on state=floating

bspc monitor DVI-D-0 -d 1 2 3 4 5

xset +fp /home/kacey/.local/share/fonts
xset fp rehash
xrdb -merge ~/.Xresources &
wal -R -n&
nitrogen --restore &
xsetroot -cursor_name left_ptr &
compton --config /home/kacey/.config/compton/compton.conf &
sh ~/.config/lemonbar/bar.sh &
sxhkd &
