#! /bin/bash

echo -e "\e[31mなるかみの, すこしとよみて,
 \e[35m faint clap of thunder,
\e[31mさしくもり,
 \e[35m Clouded skies,
\e[31mあめもふらぬか,
 \e[35m Perhaps rain will come.
\e[31mきみをとどめむ?
 \e[35m If so, will you stay here with me?
 
\e[31mなるかみの, すこしとよみて,
 \e[35m A faint clap of thunder,
\e[31mふらずとも,
 \e[35m Even if rain comes or not,
\e[31mわはとどまらむ,
 \e[35m I will stay here,
\e[31mいもしとどめば。
 \e[35m Together with you."
